/**
 * Aeropuertos peruanos con coordenadas precisas.
 * Fuente: AIP PERU ENR 2 / AD 2 (extraído del sistema de referencia).
 * Usado por el mapa interactivo cuando /api/airports no tiene coords.
 */

export interface PeruvianAirport {
  icao: string
  iata?: string
  name: string
  short?: string
  city: string
  dept?: string
  lat: number
  lng: number
  elev?: number
  magVar?: number
  transAlt?: number
  transLvl?: string
  cert?: string
  aftn?: string
}

export const PERUVIAN_AIRPORTS: PeruvianAirport[] = [
  {
    "icao": "SPIM",
    "iata": "LIM",
    "name": "Aeropuerto Internacional Jorge Chávez",
    "short": "Jorge Chávez",
    "city": "Callao",
    "dept": "Callao",
    "lat": -12.0219,
    "lng": -77.1143,
    "elev": 113,
    "magVar": 1.2,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "INTERNACIONAL",
    "aftn": "SPIMZPZX"
  },
  {
    "icao": "SPZO",
    "iata": "CUZ",
    "name": "Aeropuerto Internacional Teniente FAP Alejandro Velasco Astete",
    "short": "Velasco Astete",
    "city": "Cusco",
    "dept": "Cusco",
    "lat": -13.5357,
    "lng": -71.9388,
    "elev": 10860,
    "magVar": -5.0,
    "transAlt": 18000,
    "transLvl": "Por ATC (ATZ hasta 14500ft)",
    "cert": "INTERNACIONAL",
    "aftn": "SPZOYDYX"
  },
  {
    "icao": "SPQU",
    "iata": "AQP",
    "name": "Aeropuerto Internacional Rodríguez Ballón",
    "short": "Rodríguez Ballón",
    "city": "Arequipa",
    "dept": "Arequipa",
    "lat": -16.3411,
    "lng": -71.583,
    "elev": 8405,
    "magVar": 1.5,
    "transAlt": 18000,
    "transLvl": "FL250",
    "cert": "INTERNACIONAL",
    "aftn": "SPQUZPZX"
  },
  {
    "icao": "SPJL",
    "iata": "JUL",
    "name": "Aeropuerto Internacional Inca Manco Cápac",
    "short": "Manco Cápac",
    "city": "Juliaca",
    "dept": "Puno",
    "lat": -15.4671,
    "lng": -70.1583,
    "elev": 12552,
    "magVar": 2.3,
    "transAlt": 18000,
    "transLvl": "FL290",
    "cert": "INTERNACIONAL",
    "aftn": "SPJLZPZX"
  },
  {
    "icao": "SPTU",
    "iata": "PEM",
    "name": "Aeropuerto Internacional Padre Aldamiz",
    "short": "Padre Aldamiz",
    "city": "Puerto Maldonado",
    "dept": "Madre de Dios",
    "lat": -12.6136,
    "lng": -69.2286,
    "elev": 659,
    "magVar": 2.1,
    "transAlt": 18000,
    "transLvl": "FL180",
    "cert": "INTERNACIONAL",
    "aftn": "SPTU"
  },
  {
    "icao": "SPRU",
    "iata": "TRU",
    "name": "Aeropuerto Internacional Cap. FAP Carlos Martínez de Pinillos",
    "short": "Martínez de Pinillos",
    "city": "Trujillo",
    "dept": "La Libertad",
    "lat": -8.0814,
    "lng": -79.1088,
    "elev": 97,
    "magVar": 1.0,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "INTERNACIONAL",
    "aftn": "SPRUZPZX"
  },
  {
    "icao": "SPHI",
    "iata": "CIX",
    "name": "Aeropuerto Internacional Cap. FAP José A. Quiñones González",
    "short": "Quiñones",
    "city": "Chiclayo",
    "dept": "Lambayeque",
    "lat": -6.7875,
    "lng": -79.8281,
    "elev": 98,
    "magVar": 1.0,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "INTERNACIONAL",
    "aftn": "SPHIZPZX"
  },
  {
    "icao": "SPQT",
    "iata": "IQT",
    "name": "Aeropuerto Internacional Crnl. FAP Francisco Secada Vignetta",
    "short": "Secada Vignetta",
    "city": "Iquitos",
    "dept": "Loreto",
    "lat": -3.7847,
    "lng": -73.3088,
    "elev": 126,
    "magVar": 2.1,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "INTERNACIONAL",
    "aftn": "SPQTZPZX"
  },
  {
    "icao": "SPTN",
    "iata": "TCQ",
    "name": "Aeropuerto Internacional Crnl. FAP Carlos Ciriani Santa Rosa",
    "short": "Ciriani",
    "city": "Tacna",
    "dept": "Tacna",
    "lat": -18.0533,
    "lng": -70.2758,
    "elev": 1538,
    "magVar": 1.8,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "INTERNACIONAL",
    "aftn": "SPTN"
  },
  {
    "icao": "SPHO",
    "iata": "AYP",
    "name": "Aeropuerto Crnl. FAP Alfredo Mendívil Duarte",
    "short": "Mendívil",
    "city": "Ayacucho",
    "dept": "Ayacucho",
    "lat": -13.1548,
    "lng": -74.2044,
    "elev": 8919,
    "magVar": 1.9,
    "transAlt": 18000,
    "transLvl": "FL260",
    "cert": "NACIONAL",
    "aftn": "SPHO"
  },
  {
    "icao": "SPST",
    "iata": "TPP",
    "name": "Aeropuerto Cad. FAP Guillermo del Castillo Paredes",
    "short": "Del Castillo",
    "city": "Tarapoto",
    "dept": "San Martín",
    "lat": -6.5087,
    "lng": -76.3738,
    "elev": 869,
    "magVar": 1.9,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "NACIONAL",
    "aftn": "SPST"
  },
  {
    "icao": "SPJR",
    "iata": "CJA",
    "name": "Aeropuerto My. Gral. FAP Armando Revoredo Iglesias",
    "short": "Revoredo",
    "city": "Cajamarca",
    "dept": "Cajamarca",
    "lat": -7.1392,
    "lng": -78.4894,
    "elev": 8781,
    "magVar": 1.1,
    "transAlt": 18000,
    "transLvl": "FL260",
    "cert": "NACIONAL",
    "aftn": "SPJR"
  },
  {
    "icao": "SPHY",
    "iata": "ANS",
    "name": "Aeropuerto de Andahuaylas",
    "short": "Andahuaylas",
    "city": "Andahuaylas",
    "dept": "Apurímac",
    "lat": -13.7064,
    "lng": -73.3503,
    "elev": 11300,
    "magVar": 2.0,
    "transAlt": 18000,
    "transLvl": "FL270",
    "cert": "NACIONAL",
    "aftn": "SPHY"
  },
  {
    "icao": "SPSO",
    "iata": "PIO",
    "name": "Aeropuerto Cap. FAP Renán Elías Olivera",
    "short": "Renán Elías",
    "city": "Pisco",
    "dept": "Ica",
    "lat": -13.7449,
    "lng": -76.2203,
    "elev": 39,
    "magVar": 1.3,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "NACIONAL",
    "aftn": "SPSO"
  },
  {
    "icao": "SPMS",
    "iata": "YMS",
    "name": "Aeropuerto Moisés Benzaquen Rengifo",
    "short": "Benzaquen",
    "city": "Yurimaguas",
    "dept": "Loreto",
    "lat": -5.8937,
    "lng": -76.1182,
    "elev": 587,
    "magVar": 1.9,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "NACIONAL",
    "aftn": "SPMS"
  },
  {
    "icao": "SPUR",
    "iata": "PIU",
    "name": "Aeropuerto Internacional Cap. FAP Guillermo Concha Iberico",
    "short": "Concha Iberico",
    "city": "Piura",
    "dept": "Piura",
    "lat": -5.2056,
    "lng": -80.6167,
    "elev": 116,
    "magVar": 1.0,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "INTERNACIONAL",
    "aftn": "SPURZPZX"
  },
  {
    "icao": "SPCL",
    "iata": "PCL",
    "name": "Aeropuerto Internacional Cap. FAP David Abenzur Rengifo",
    "short": "Abenzur",
    "city": "Pucallpa",
    "dept": "Ucayali",
    "lat": -8.3779,
    "lng": -74.5744,
    "elev": 154,
    "magVar": 1.8,
    "transAlt": 18000,
    "transLvl": "FL200",
    "cert": "INTERNACIONAL",
    "aftn": "SPCL"
  },
  {
    "icao": "SPPY",
    "iata": "CHH",
    "name": "Aeropuerto de Chachapoyas",
    "short": "Chachapoyas",
    "city": "Chachapoyas",
    "dept": "Amazonas",
    "lat": -6.2018,
    "lng": -77.8561,
    "elev": 8333,
    "magVar": 1.5,
    "transAlt": 18000,
    "transLvl": "FL260",
    "cert": "NACIONAL",
    "aftn": "SPPY"
  },
  {
    "icao": "SPYL",
    "iata": "TYL",
    "name": "Aeropuerto Internacional Capitán FAP Víctor Montes",
    "short": "Víctor Montes",
    "city": "Talara",
    "dept": "Piura",
    "lat": -4.576611,
    "lng": -81.254058,
    "elev": 282,
    "magVar": -1.0,
    "transAlt": 10000,
    "transLvl": "Por ATC",
    "cert": "INTERNACIONAL",
    "aftn": "SPYLYDYX"
  },
  {
    "icao": "SPNC",
    "iata": "HUU",
    "name": "Aeropuerto Alférez FAP David Figueroa Fernandini",
    "short": "Figueroa",
    "city": "Huánuco",
    "dept": "Huánuco",
    "lat": -9.8788,
    "lng": -76.2048,
    "elev": 6069,
    "magVar": 1.7,
    "transAlt": 18000,
    "transLvl": "FL230",
    "cert": "NACIONAL",
    "aftn": "SPNC"
  },
  {
    "icao": "SPAS",
    "name": "ANDOAS",
    "city": "ANDOAS",
    "dept": "Loreto",
    "lat": -2.796108333333333,
    "lng": -76.46659722222222,
    "elev": 728,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPHZ",
    "name": "COMANDANTE FAP GERMÁN ARIAS GRAZIANI",
    "city": "ANTA HUARAZ",
    "dept": "Ancash",
    "lat": -9.360555555555555,
    "lng": -77.59388888888888,
    "elev": 9015,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPAY",
    "name": "ATALAYA",
    "city": "ATALAYA",
    "dept": "Ucayali",
    "lat": -10.72861111111111,
    "lng": -73.76611111111112,
    "elev": 1900,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPEO",
    "name": "TENIENTE FAP JAIME A. DE MONTREUIL MORALES",
    "city": "CHIMBOTE",
    "dept": "Ancash",
    "lat": -9.151166666666667,
    "lng": -78.52383333333333,
    "elev": 69,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPJE",
    "name": "FERNANDO BELAÚNDE TERRY",
    "city": "JAÉN",
    "dept": "Cajamarca",
    "lat": -5.591388888888889,
    "lng": -78.7713888888889,
    "elev": 2477,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPJJ",
    "name": "FRANCISCO CARLÉ",
    "city": "JAUJA",
    "dept": "Junín",
    "lat": -11.783388888888888,
    "lng": -75.47336111111112,
    "elev": 11034,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPJI",
    "name": "JUANJUÍ",
    "city": "JUANJUÍ",
    "dept": "San Martín",
    "lat": -7.169722222222222,
    "lng": -76.72916666666667,
    "elev": 1148,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPMF",
    "name": "MAYOR PNP NANCY FLORES PÁUCAR",
    "city": "MAZAMARI",
    "dept": "Junín",
    "lat": -11.325516666666667,
    "lng": -74.53582777777778,
    "elev": 2180,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPJA",
    "name": "AERÓDROMO RIOJA",
    "city": "RIOJA",
    "dept": "San Martín",
    "lat": -6.0677916666666665,
    "lng": -77.15980555555556,
    "elev": 2707,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPGM",
    "name": "AERÓDROMO TINGO MARÍA",
    "city": "TINGO MARÍA",
    "dept": "Huánuco",
    "lat": -9.289666666666667,
    "lng": -76.00505555555556,
    "elev": 2146,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPLO",
    "name": "AEROPUERTO GENERAL JORGE FERNÁNDEZ MALDONADO SOLARI",
    "city": "ILO",
    "dept": "Moquegua",
    "lat": -17.695,
    "lng": -71.34388888888888,
    "elev": 72,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPZA",
    "name": "AEROPUERTO NACIONAL MARÍA REICHE NEUMAN",
    "city": "NASCA",
    "dept": "Ica",
    "lat": -14.854138888888889,
    "lng": -74.96177222222222,
    "elev": 1813,
    "cert": "NACIONAL"
  },
  {
    "icao": "SPME",
    "name": "AEROPUERTO CAPITÁN FAP PEDRO CANGA RODRÍGUEZ",
    "city": "TUMBES",
    "dept": "Tumbes",
    "lat": -3.5522638888888887,
    "lng": -80.38106944444444,
    "elev": 115,
    "cert": "NACIONAL"
  },
]
