/**
 * Pobla datos de servicios faltantes (MET, combustibles, pasajeros, etc.)
 * para aeropuertos que tienen estos campos como NULL.
 *
 * Datos extraídos del AIP Perú y fuentes oficiales CORPAC S.A.
 */
import { db } from "@/lib/db"

interface ServiceData {
  icao: string
  metOffice?: string
  metHours?: string
  metForecastOffice?: string
  metValidity?: string
  metLandingForecast?: string
  metTrendInterval?: string
  metBriefing?: string
  metConsultation?: string
  metDocumentation?: string
  metLanguage?: string
  metSupplementary?: string
  metAtsDependencies?: string
  metAdditionalInfo?: string
  rescueEquipment?: string
  aircraftRemovalCapacity?: string
  cargoHandlingFacilities?: string
  hotels?: string
  restaurants?: string
  transport?: string
  medicalFacilities?: string
  bankingPost?: string
  tourismOffice?: string
}

const serviceData: ServiceData[] = [
  {
    icao: "SPME",
    metOffice: "OMA SPME",
    metHours: "1500 - 0300",
    metForecastOffice: "OMA/SPME",
    metValidity: "24 h",
    metLandingForecast: "TREND",
    metTrendInterval: "Cada hora",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA",
    metLanguage: "Español / Inglés",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "SPME TWR, LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo completo de rescate CAT 7",
    aircraftRemovalCapacity: "Provisto por compañía particular",
    cargoHandlingFacilities: "Instalaciones para manipulación de carga proporcionadas por compañías particulares",
    hotels: "Hoteles disponibles en la ciudad de Tumbes",
    restaurants: "Locales de comidas y bebidas en el terminal y en la ciudad",
    transport: "Empresas de transporte terrestre (taxi, rent a car) en llegadas",
    medicalFacilities: "Primeros auxilios en el AD y hospitales en la ciudad",
    bankingPost: "Oficina bancaria y puesto de cambio de divisas en el terminal",
    tourismOffice: "Oficina de turismo en el AD y la ciudad",
  },
  {
    icao: "SPAS",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPQU",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPQU",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "SPAS TWR, LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 5",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPAY",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPZO",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPZO",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPEO",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPQU",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPQU",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPGM",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPJC",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPJC",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPHO",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPHI",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPHI",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "SPHO TWR, LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 5",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPHY",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPJC",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPJC",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPHZ",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPZO",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPZO",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPJA",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPQU",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPQU",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPJE",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPJC",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPJC",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPJI",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPQU",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPQU",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPJJ",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPJC",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPJC",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPJR",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPQU",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPQU",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPMF",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPJC",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPJC",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPMS",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPJC",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPJC",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPNC",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPQU",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPQU",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPPY",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPQU",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPQU",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPTU",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPZO",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPZO",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
  {
    icao: "SPUR",
    metOffice: "NIL",
    metHours: "H24",
    metForecastOffice: "OMA/SPJC",
    metValidity: "24 h",
    metLandingForecast: "NIL",
    metTrendInterval: "NIL",
    metBriefing: "O/R",
    metConsultation: "O/R",
    metDocumentation: "Proporcionada por OMA SPJC",
    metLanguage: "Español",
    metSupplementary: "SIGMET, AIRMET, NOTAM",
    metAtsDependencies: "LIMA ACC",
    metAdditionalInfo: "NIL",
    rescueEquipment: "Equipo de rescate CAT 4",
    aircraftRemovalCapacity: "NIL",
    cargoHandlingFacilities: "NIL",
    hotels: "Disponibles en la ciudad",
    restaurants: "Disponibles en la ciudad",
    transport: "Transporte terrestre en la ciudad",
    medicalFacilities: "Primeros auxilios en el AD",
    bankingPost: "NIL",
    tourismOffice: "NIL",
  },
]

async function main() {
  console.log("═".repeat(70))
  console.log("Poblando datos de servicios faltantes")
  console.log("═".repeat(70))

  let updatedCount = 0

  for (const item of serviceData) {
    const airport = await db.airport.findUnique({ where: { icaoCode: item.icao } })
    if (!airport) {
      console.log(`✗ ${item.icao}: aeropuerto no encontrado`)
      continue
    }

    const data: Record<string, string> = {}
    const fields = [
      "metOffice", "metHours", "metForecastOffice", "metValidity", "metLandingForecast",
      "metTrendInterval", "metBriefing", "metConsultation", "metDocumentation",
      "metLanguage", "metSupplementary", "metAtsDependencies", "metAdditionalInfo",
      "rescueEquipment", "aircraftRemovalCapacity", "cargoHandlingFacilities",
      "hotels", "restaurants", "transport", "medicalFacilities", "bankingPost", "tourismOffice"
    ]

    for (const f of fields) {
      const v = (item as Record<string, string | undefined>)[f]
      if (v !== undefined && !airport[f as keyof typeof airport]) {
        data[f] = v
      }
    }

    if (Object.keys(data).length > 0) {
      await db.airport.update({
        where: { icaoCode: item.icao },
        data,
      })
      console.log(`✓ ${item.icao}: ${Object.keys(data).length} campos actualizados`)
      updatedCount++
    } else {
      console.log(`• ${item.icao}: sin cambios necesarios`)
    }
  }

  console.log("═".repeat(70))
  console.log(`RESUMEN: ${updatedCount} aeropuertos actualizados`)
  console.log("═".repeat(70))

  await db.$disconnect()
}

main()
  .then(() => process.exit(0))
  .catch((e: unknown) => {
    console.error("Error:", e)
    process.exit(1)
  })
